pipeline {
    agent any
    stages {
        stage('front end testing , building docker image and push to github Registry'){
        steps{
        dir("budget-tracker/client"){
            sh "npm install && npm run test"
        }
        }
        }
        stage('Build user-service') {
            steps {
                dir("budget-tracker/services/user-service") {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test user-service') {
            steps {
                dir("budget-tracker/services/user-service") {
                    sh 'mvn test'
                }
            }
        }
        stage('Building and Push Docker Image to Github Registry') {
        environment {
                    registry = "docker.pkg.github.com/narenraj701/bootcamp3-test/user"
                    dockerImage=''
                  }
              steps{
              dir("budget-tracker/services/user-service"){
              script {
                         dockerImage = docker.build registry + ":$BUILD_NUMBER"
                       }
                        sh 'echo ${GH_TOKEN} | docker login docker.pkg.github.com -u narenraj701 --password-stdin'
                        sh 'docker push '+registry+":$BUILD_NUMBER"
              }
              }
            }
        stage('Build budget-service') {
                    steps {
                        dir("budget-tracker/services/budget-service") {
                            sh 'mvn -B -DskipTests clean package'
                        }
                    }
                }
                stage('Test budget-service') {
                    steps {
                        dir("budget-tracker/services/budget-service") {
                            sh 'mvn test'
                        }
                    }
                }
                stage('Build transaction-service') {
                            steps {
                                dir("budget-tracker/services/transaction-service") {
                                    sh 'mvn -B -DskipTests clean package'
                                }
                            }
                        }
                        stage('Test transaction-service') {
                            steps {
                                dir("budget-tracker/services/transaction-service") {
                                    sh 'mvn test'
                                }
                            }
                        }
                        stage('Build notification-service') {
                                    steps {
                                        dir("budget-tracker/services/notification-service") {
                                            sh 'mvn -B -DskipTests clean package'
                                        }
                                    }
                                }
                                stage('Test notification-service') {
                                    steps {
                                        dir("budget-tracker/services/notification-service") {
                                            sh 'mvn test'
                                        }
                                    }
                                }
    }
}